### ISSUE TITLE
Can not reproduce the example

### ISSUE THREAD

**Issue by shayandavoodii** [lstagner/FastKmeans.jl#2]
Hi,
[Here](https://github.com/lstagner/FastKmeans.jl#example) you provided an example of your script. You used a package named `Iterators` in it. It doesn't exist anymore, and I guess it's essential in creating the `linspace(-1,1,10)`. So can you please tell me what is the shape of `p` in the example? Is it a vector?

**Comment by lstagner** [comment]
`p` is a vector of vectors e.g. `[[1,1],[1,2],...]`. It later gets turned into a `2xN` matrix for the classic clustering algorithm. Anyway, I updated the example so that it should work (though I haven't tested it). The main issue is that the `product` function moved into `Base.Iterators`. 

```julia
julia> using Clustering, FastKmeans, Base.Iterators

julia> x = range(-1,1,length=10)

julia> p = Vector{Float64}[]; sizehint!(p,20_000_000)

julia> for xc in product(x,x)
           xx = collect(xc)
           append!(p,[xx .+ 0.04*randn(2) for i=1:12500])
       end

julia> p_matrix = hcat(p...);

julia> @time a, centers = fastkmeans(p,100);
 7.415347 seconds (126.25 M allocations: 5.718 GB, 11.89% gc time)

julia> @time k = Clustering.kmeans(p_matrix,100);
 54.080827 seconds (125.01 M allocations: 33.686 GB, 2.93% gc time)
```

**Comment by shayandavoodii** [comment]
> the product function moved into Base.Iterators.

Then you don't need to write `using Base.Iterators` since all the Base functions are available at any time.  
And, I get the following error: `ERROR: UndefVarError: dot not defined`. It's related to the following line `d1 = dot(yy,yy)` in the `point_all_ctrs!` function.

**Comment by lstagner** [comment]
Ok I have updated the repo for julia 1.8 everything should work now.
